### ISSUE TITLE
logcatplusplus.readOnlyFile false does not work

### ISSUE THREAD

**Issue by murder** [jeymichael/vscodelogcat#2]
Wehen setting `logcatplusplus.readOnlyFile` to `false` the files are still readonly.

Please fix or give a command on command palette to deactivate it

@jeymichael this extension has potential

**Comment by Albinoman887** [comment]
i fixed it and made a pull reqauest here: https://github.com/jeymichael/vscodelogcat/pull/3

**Comment by jeymichael** [comment]
Ah.. let me hunt down my workspace to re-deploy the extension.  
I had the default to off, in the previous version, and never came back to my workspace to address this.  Will be able to do the patch/deploy, this week.

**Comment by jeymichael** [comment]
Fixed the code to honor the flag.  Defaulted the flag to false.  Deployed in ver 0.0.5

**Comment by jeymichael** [comment]
Closing.  Fix deployed in ver 0.0.5
